### ISSUE TITLE
.gitignore 

### ISSUE THREAD

**Issue by andreinechaev** [MaximAba/TestHello#1]
Используй `.gitignore` для исключения ненужных файлов и папок, например `.idea`

**Comment by andreinechaev** [comment]
пример:
https://github.com/andreinechaev/AkkaPlayground/blob/master/.gitignore

можешь пользовать https://www.gitignore.io дл создания темплейтов или установить плагин для IDEA

**Comment by MaximAba** [comment]
Сделано
